from exception import BadName, greet

print(BadName)
print(greet)